/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as ProviderRouteImport } from './routes/provider'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as MemoriesRouteImport } from './routes/memories'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JoinUsRouteImport } from './routes/join-us'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProviderNewRouteImport } from './routes/provider.new'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderRoute = ProviderRouteImport.update({
  id: '/provider',
  path: '/provider',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoriesRoute = MemoriesRouteImport.update({
  id: '/memories',
  path: '/memories',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinUsRoute = JoinUsRouteImport.update({
  id: '/join-us',
  path: '/join-us',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderNewRoute = ProviderNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ProviderRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/bookings': typeof BookingsRoute
  '/join-us': typeof JoinUsRoute
  '/login': typeof LoginRoute
  '/memories': typeof MemoriesRoute
  '/plan': typeof PlanRoute
  '/provider': typeof ProviderRouteWithChildren
  '/verify-email': typeof VerifyEmailRoute
  '/provider/new': typeof ProviderNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/bookings': typeof BookingsRoute
  '/join-us': typeof JoinUsRoute
  '/login': typeof LoginRoute
  '/memories': typeof MemoriesRoute
  '/plan': typeof PlanRoute
  '/provider': typeof ProviderRouteWithChildren
  '/verify-email': typeof VerifyEmailRoute
  '/provider/new': typeof ProviderNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/bookings': typeof BookingsRoute
  '/join-us': typeof JoinUsRoute
  '/login': typeof LoginRoute
  '/memories': typeof MemoriesRoute
  '/plan': typeof PlanRoute
  '/provider': typeof ProviderRouteWithChildren
  '/verify-email': typeof VerifyEmailRoute
  '/provider/new': typeof ProviderNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/bookings'
    | '/join-us'
    | '/login'
    | '/memories'
    | '/plan'
    | '/provider'
    | '/verify-email'
    | '/provider/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/bookings'
    | '/join-us'
    | '/login'
    | '/memories'
    | '/plan'
    | '/provider'
    | '/verify-email'
    | '/provider/new'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/bookings'
    | '/join-us'
    | '/login'
    | '/memories'
    | '/plan'
    | '/provider'
    | '/verify-email'
    | '/provider/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BookingsRoute: typeof BookingsRoute
  JoinUsRoute: typeof JoinUsRoute
  LoginRoute: typeof LoginRoute
  MemoriesRoute: typeof MemoriesRoute
  PlanRoute: typeof PlanRoute
  ProviderRoute: typeof ProviderRouteWithChildren
  VerifyEmailRoute: typeof VerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider': {
      id: '/provider'
      path: '/provider'
      fullPath: '/provider'
      preLoaderRoute: typeof ProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memories': {
      id: '/memories'
      path: '/memories'
      fullPath: '/memories'
      preLoaderRoute: typeof MemoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join-us': {
      id: '/join-us'
      path: '/join-us'
      fullPath: '/join-us'
      preLoaderRoute: typeof JoinUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider/new': {
      id: '/provider/new'
      path: '/new'
      fullPath: '/provider/new'
      preLoaderRoute: typeof ProviderNewRouteImport
      parentRoute: typeof ProviderRoute
    }
  }
}

interface ProviderRouteChildren {
  ProviderNewRoute: typeof ProviderNewRoute
}

const ProviderRouteChildren: ProviderRouteChildren = {
  ProviderNewRoute: ProviderNewRoute,
}

const ProviderRouteWithChildren = ProviderRoute._addFileChildren(
  ProviderRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BookingsRoute: BookingsRoute,
  JoinUsRoute: JoinUsRoute,
  LoginRoute: LoginRoute,
  MemoriesRoute: MemoriesRoute,
  PlanRoute: PlanRoute,
  ProviderRoute: ProviderRouteWithChildren,
  VerifyEmailRoute: VerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
