/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as ProviderRouteImport } from './routes/provider'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as MemoriesRouteImport } from './routes/memories'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JoinUsRouteImport } from './routes/join-us'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlacesIndexRouteImport } from './routes/places.index'
import { Route as ProviderNewRouteImport } from './routes/provider.new'
import { Route as PlacesSubmitRouteImport } from './routes/places.submit'
import { Route as PlacesCommunityRouteImport } from './routes/places.community'
import { Route as PlacesSlugRouteImport } from './routes/places.$slug'
import { Route as ListingIdRouteImport } from './routes/listing.$id'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderRoute = ProviderRouteImport.update({
  id: '/provider',
  path: '/provider',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoriesRoute = MemoriesRouteImport.update({
  id: '/memories',
  path: '/memories',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinUsRoute = JoinUsRouteImport.update({
  id: '/join-us',
  path: '/join-us',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacesIndexRoute = PlacesIndexRouteImport.update({
  id: '/places/',
  path: '/places/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderNewRoute = ProviderNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ProviderRoute,
} as any)
const PlacesSubmitRoute = PlacesSubmitRouteImport.update({
  id: '/places/submit',
  path: '/places/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacesCommunityRoute = PlacesCommunityRouteImport.update({
  id: '/places/community',
  path: '/places/community',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacesSlugRoute = PlacesSlugRouteImport.update({
  id: '/places/$slug',
  path: '/places/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingIdRoute = ListingIdRouteImport.update({
  id: '/listing/$id',
  path: '/listing/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/bookings': typeof BookingsRoute
  '/join-us': typeof JoinUsRoute
  '/login': typeof LoginRoute
  '/memories': typeof MemoriesRoute
  '/messages': typeof MessagesRoute
  '/plan': typeof PlanRoute
  '/provider': typeof ProviderRouteWithChildren
  '/verify': typeof VerifyRoute
  '/verify-email': typeof VerifyEmailRoute
  '/listing/$id': typeof ListingIdRoute
  '/places/$slug': typeof PlacesSlugRoute
  '/places/community': typeof PlacesCommunityRoute
  '/places/submit': typeof PlacesSubmitRoute
  '/provider/new': typeof ProviderNewRoute
  '/places/': typeof PlacesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/bookings': typeof BookingsRoute
  '/join-us': typeof JoinUsRoute
  '/login': typeof LoginRoute
  '/memories': typeof MemoriesRoute
  '/messages': typeof MessagesRoute
  '/plan': typeof PlanRoute
  '/provider': typeof ProviderRouteWithChildren
  '/verify': typeof VerifyRoute
  '/verify-email': typeof VerifyEmailRoute
  '/listing/$id': typeof ListingIdRoute
  '/places/$slug': typeof PlacesSlugRoute
  '/places/community': typeof PlacesCommunityRoute
  '/places/submit': typeof PlacesSubmitRoute
  '/provider/new': typeof ProviderNewRoute
  '/places': typeof PlacesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/bookings': typeof BookingsRoute
  '/join-us': typeof JoinUsRoute
  '/login': typeof LoginRoute
  '/memories': typeof MemoriesRoute
  '/messages': typeof MessagesRoute
  '/plan': typeof PlanRoute
  '/provider': typeof ProviderRouteWithChildren
  '/verify': typeof VerifyRoute
  '/verify-email': typeof VerifyEmailRoute
  '/listing/$id': typeof ListingIdRoute
  '/places/$slug': typeof PlacesSlugRoute
  '/places/community': typeof PlacesCommunityRoute
  '/places/submit': typeof PlacesSubmitRoute
  '/provider/new': typeof ProviderNewRoute
  '/places/': typeof PlacesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/bookings'
    | '/join-us'
    | '/login'
    | '/memories'
    | '/messages'
    | '/plan'
    | '/provider'
    | '/verify'
    | '/verify-email'
    | '/listing/$id'
    | '/places/$slug'
    | '/places/community'
    | '/places/submit'
    | '/provider/new'
    | '/places/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/bookings'
    | '/join-us'
    | '/login'
    | '/memories'
    | '/messages'
    | '/plan'
    | '/provider'
    | '/verify'
    | '/verify-email'
    | '/listing/$id'
    | '/places/$slug'
    | '/places/community'
    | '/places/submit'
    | '/provider/new'
    | '/places'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/bookings'
    | '/join-us'
    | '/login'
    | '/memories'
    | '/messages'
    | '/plan'
    | '/provider'
    | '/verify'
    | '/verify-email'
    | '/listing/$id'
    | '/places/$slug'
    | '/places/community'
    | '/places/submit'
    | '/provider/new'
    | '/places/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BookingsRoute: typeof BookingsRoute
  JoinUsRoute: typeof JoinUsRoute
  LoginRoute: typeof LoginRoute
  MemoriesRoute: typeof MemoriesRoute
  MessagesRoute: typeof MessagesRoute
  PlanRoute: typeof PlanRoute
  ProviderRoute: typeof ProviderRouteWithChildren
  VerifyRoute: typeof VerifyRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  ListingIdRoute: typeof ListingIdRoute
  PlacesSlugRoute: typeof PlacesSlugRoute
  PlacesCommunityRoute: typeof PlacesCommunityRoute
  PlacesSubmitRoute: typeof PlacesSubmitRoute
  PlacesIndexRoute: typeof PlacesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider': {
      id: '/provider'
      path: '/provider'
      fullPath: '/provider'
      preLoaderRoute: typeof ProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memories': {
      id: '/memories'
      path: '/memories'
      fullPath: '/memories'
      preLoaderRoute: typeof MemoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join-us': {
      id: '/join-us'
      path: '/join-us'
      fullPath: '/join-us'
      preLoaderRoute: typeof JoinUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/places/': {
      id: '/places/'
      path: '/places'
      fullPath: '/places/'
      preLoaderRoute: typeof PlacesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider/new': {
      id: '/provider/new'
      path: '/new'
      fullPath: '/provider/new'
      preLoaderRoute: typeof ProviderNewRouteImport
      parentRoute: typeof ProviderRoute
    }
    '/places/submit': {
      id: '/places/submit'
      path: '/places/submit'
      fullPath: '/places/submit'
      preLoaderRoute: typeof PlacesSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/places/community': {
      id: '/places/community'
      path: '/places/community'
      fullPath: '/places/community'
      preLoaderRoute: typeof PlacesCommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/places/$slug': {
      id: '/places/$slug'
      path: '/places/$slug'
      fullPath: '/places/$slug'
      preLoaderRoute: typeof PlacesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listing/$id': {
      id: '/listing/$id'
      path: '/listing/$id'
      fullPath: '/listing/$id'
      preLoaderRoute: typeof ListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProviderRouteChildren {
  ProviderNewRoute: typeof ProviderNewRoute
}

const ProviderRouteChildren: ProviderRouteChildren = {
  ProviderNewRoute: ProviderNewRoute,
}

const ProviderRouteWithChildren = ProviderRoute._addFileChildren(
  ProviderRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BookingsRoute: BookingsRoute,
  JoinUsRoute: JoinUsRoute,
  LoginRoute: LoginRoute,
  MemoriesRoute: MemoriesRoute,
  MessagesRoute: MessagesRoute,
  PlanRoute: PlanRoute,
  ProviderRoute: ProviderRouteWithChildren,
  VerifyRoute: VerifyRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  ListingIdRoute: ListingIdRoute,
  PlacesSlugRoute: PlacesSlugRoute,
  PlacesCommunityRoute: PlacesCommunityRoute,
  PlacesSubmitRoute: PlacesSubmitRoute,
  PlacesIndexRoute: PlacesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
